theme: jekyll-theme-primer
title: 2017 APCOMP 209A, Group 48
description: 2017 APCOMP 209A Group 48's Recommendations Project
baseurl:
markdown: kramdown
kramdown:
    math_engine: mathjax
    input: GFM
    syntax_highlighter: rouge
